import type { CSSProperties, ReactNode } from "react";

import type {
    AppNotificationVisibilityChangeReason,
    BaseAppNotificationProps,
} from "./BaseAppNotification";

/**
 * Single notification entry managed by the NotificationCenter.
 * It reuses AppNotificationProps but adds a required `id` and
 * an optional per-item dismiss handler.
 */
export interface NotificationCenterItem
    extends Omit<
        BaseAppNotificationProps,
        "onDismiss" | "visible" | "defaultVisible" | "onVisibleChange"
    > {
    /** Unique identifier for the notification inside the center */
    id: string;

    /**
     * Optional grace period before removing a notification when its source
     * component unmounts. Useful to avoid flicker during transient state flips.
     */
    lingerMs?: number;

    /**
     * Optional per-item dismiss handler.
     * This is called before the center-level onNotificationDismiss.
     */
    itemOnDismiss?: BaseAppNotificationProps["onDismiss"];
}

/**
 * Props for the presentational NotificationCenter component.
 * In esta etapa básica no hay grouping ni pinned, solo lista plana.
 */
export interface NotificationCenterProps {
    /** List of notifications to display */
    notifications: NotificationCenterItem[];

    /**
     * Called when a notification is dismissed (manual or auto).
     * Normalmente el provider/parent usa esto para remover el item del array.
     */
    onNotificationDismiss?: (
        id: string,
        reason: AppNotificationVisibilityChangeReason
    ) => void;

    /** Optional className for the outer container */
    className?: string;

    /** Optional inline styles for the container */
    style?: CSSProperties;

    /**
     * Optional custom renderer in case you want to wrap each notification
     * with animations or extra markup in the future.
     */
    renderItem?: (item: NotificationCenterItem) => ReactNode;
}

/**
 * Options accepted by the high-level `notify()` API.
 * Very similar to NotificationCenterItem, but without `id` and `itemOnDismiss`.
 */
export interface CreateNotificationOptions
    extends Omit<NotificationCenterItem, "id" | "itemOnDismiss"> {
    /** Optional custom id, otherwise it will be autogenerated */
    id?: string;

    /** Optional onDismiss handler at creation time */
    onDismiss?: BaseAppNotificationProps["onDismiss"];
}

/**
 * Shape of the value exposed by the NotificationContext.
 */
export interface NotificationContextValue {
    notifications: NotificationCenterItem[];

    /** Push a new notification to the center. Returns the generated id. */
    notify: (options: CreateNotificationOptions) => string;

    /** Programmatically dismiss a notification by id */
    dismiss: (
        id: string,
        reason?: AppNotificationVisibilityChangeReason
    ) => void;

    /** Clear all notifications */
    clearAll: () => void;
}

/**
 * Props for the GlobalNotificationCenter, which reads data from context.
 * Mirrors NotificationCenterProps minus notifications & onNotificationDismiss.
 */
export type GlobalNotificationCenterProps = Omit<
    NotificationCenterProps,
    "notifications" | "onNotificationDismiss"
>;
